import { CardGrid } from '../components/CardGrid';
import { Section } from '../components/Section';
import type { CardItem } from '../types';

const projects: CardItem[] = [
  { title: "Anscombe's Quartet Research", href: 'https://github.com/axyl-casc/Anscombes_Research?tab=readme-ov-file#anscombes-quartet-research-project', description: "Created a program to replicate Anscombe's Quartet, emphasizing the importance of visual data analysis." },
  { title: 'Infinite Mind Games – Wiki Docs', href: 'https://infinite-mind-pictures-inc.github.io/Infinite-Mind-Wiki/', description: 'An interactive documentation site built with Quartz, featuring guides, learning modules, and development notes for Infinite Mind Games projects.' },
  { title: 'Beginner GO AI Game', href: 'https://zxnashx.itch.io/beginner-go-game', description: 'A GO playing interface designed to teach beginners how to play the game of GO.' },
  { title: 'Fancy Pants Outfitters (React Demo)', href: 'https://acare3.github.io/4513_2_website/', description: 'A polished React storefront demo featuring curated fashion for trendsetters, workweek looks, and night-out fits. Highlights include in-stock essentials, modern silhouettes, and standout accessories for individuals, partners, and the whole crew.' },
  { title: 'Defender Remake on Atari ST', href: 'https://github.com/axyl-casc/DefenderRemake/tree/main?tab=readme-ov-file#atari-st-game---defender', description: 'Recreated a classic arcade game using C and assembly, leveraging efficient memory management on limited hardware.' },
  { title: 'Linux Shell Development', href: 'https://github.com/axyl-casc/linux-shell?tab=readme-ov-file#linux-shell', description: 'Built a custom shell in C, handling concurrent commands and inter-process communication for a streamlined command-line experience.' },
  { title: 'Other Projects', href: '/other_projects', description: 'Explore additional projects, including software tools, data visualizations, and experimental applications.' }
];

const hobbies: CardItem[] = [
  { title: 'Baduk / GO', href: 'https://online-go.com/user/view/1071783', description: 'I enjoy studying and playing GO (Baduk), from tactical puzzles to longer, strategic games online.' },
  { title: 'Rock Climbing', href: 'https://www.instagram.com/axyl.sc/', description: 'Bouldering and climbing help me stay active, solve movement problems, and keep improving technique.' },
  { title: 'Bird Watching', href: 'https://ebird.org/profile/Nzc4Nzg0NQ', description: 'I like tracking sightings, identifying species, and exploring local habitats through birding.' }
];

export function HomePage() { return <main className="site-main"><Section title="About Me"><p>I’m a Computer Science graduate from Mount Royal University and a software developer focused on building efficient, reliable systems. I’ve delivered projects spanning legacy game development, data-driven analysis, and technical communication, and I bring a practical, outcomes-focused approach to solving problems at the intersection of performance, design, and usability.</p></Section><Section title="Technical Skills"><p>Strong in C++, Java, Python, and SQL with hands-on experience in:</p><ul className="list-disc pl-6 space-y-1"><li><strong>Software Development:</strong> Algorithm design, systems programming</li><li><strong>Data & Visualization:</strong> MySQL, Matplotlib, NumPy</li><li><strong>Teaching & Mentoring:</strong> Experience in guiding students through Python and SQL concepts</li></ul></Section><Section title="Projects"><CardGrid items={projects} /></Section><Section title="Experience"><div className="space-y-4"><div><h3 className="font-semibold">Web Development Intern, Infinite Mind Pictures Inc.</h3><p>Improved and maintained online platforms with a focus on accessibility, design quality, and user experience while building a resource portal for the creative and educational community.</p></div><div><h3 className="font-semibold">Programming Tutor, Launch Pad Learning</h3><p>Coached students in programming fundamentals, designed hands-on coding activities, and strengthened their problem-solving skills.</p></div><div><h3 className="font-semibold">Mover & IT Support, Darwins Moving & Deliveries</h3><p>Managed technical setup for clients and provided hardware/software support, developing strong troubleshooting skills.</p></div></div></Section><hr /><Section title="Hobbies"><CardGrid items={hobbies} /></Section></main>; }
